### ISSUE TITLE
Consider demangling c++ symbols

### ISSUE THREAD

**Issue by GPSBabelDeveloper** [lupyuen/remote-bl602#1]
https://github.com/lupyuen/remote-bl602/blob/1c74739432fe7dbc5c8297f1b66e43f705ee6189/scripts/test.sh#L88

I'm being lazy and not testing this code, but by inspection, I'm not sure it does the right thing with demangling C++ symbols in the stack trace. Just running the collection of test.log through `riscv64...-c++-filt `(or doing it in a later pass over the file) should get you constructor and destructor call as well as operator overloads.

It's a matter of taste where to insert that filter. Doing it here means the output you see on the terminal will be unpleasant. It may be easier to insert it at the uses down around L131 or 140.

If this script needs to be faster, you can probably harvest the symbol table from `riscv64...objdump -t `(print symbols) or the more common `riscv64...nm` - that has a zillion options of its own. That should be less expensive than passing over a full disassembly. It may not be an issue if you're running this on a "big" computer and not the BL602 itself.

`script` may be easier to wrangle than `cat` on a serial port. There tends to be fewer flushing issues as cat normally buffers data on write in large (page or so) chunks. script has special flags for writing to pipes.

Yay for tackling an underserved problem in that project. The top-of-tree was frequently broken when I tried to be involved.

**Comment by lupyuen** [comment]
Thanks for the tip, so glad we finally found a way to auto-decode BL602 stack traces :-) 

I'm doing demangling in GitHub Actions (for the daily build) when I dump the disassembly...

https://github.com/lupyuen/incubator-nuttx/blob/master/.github/workflows/bl602.yml#L71-L76

```bash
        ## Dump the disassembly to nuttx.S
        riscv64-unknown-elf-objdump \
          -t -S --demangle --line-numbers --wide \
          nuttx \
          >nuttx.S \
          2>&1
```

NuttX doesn't show the symbol names, we're actually looking up the demangled symbol names in the disassembly file. So this should already work I think?

**Comment by GPSBabelDeveloper** [comment]
Ah, it was in a different file, but it's already there. That looks like it
should handle the mangling. Awesome. We can close this.

Bugreport solved. I had some additional ideas on speeding it up, but I'll
kick that around some more.
